//! P1 canonical chunked-content vectors (design §5.3/§5.4).
//!
//! The golden bytes and root CIDs come from `conformance/vectors/p1/chunking.json`,
//! which is generated by `conformance/tools/gen_manifest_goldens.py` from
//! `protoc --encode` (C++ protobuf) plus the Python standard library — an
//! implementation sharing no code with prost or ts-proto. Both language sides
//! must reproduce these bytes exactly.
use conex_proto::cid::{
    CHUNK_SIZE, cid_for_raw, content_cid, leaf_cids_for, manifest_tree, parse_cid,
};
use serde_json::Value;

fn vectors() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../conformance/vectors/p1/chunking.json"
    );
    let text = std::fs::read_to_string(path).expect("read conformance/vectors/p1/chunking.json");
    serde_json::from_str(&text).expect("parse chunking vectors")
}

fn payload(case: &Value) -> Vec<u8> {
    let spec = &case["payload"];
    match spec["kind"].as_str().expect("payload kind") {
        "literal" => spec["value"]
            .as_str()
            .expect("literal value")
            .as_bytes()
            .to_vec(),
        "fill" => {
            let byte = spec["byte"].as_u64().expect("fill byte") as u8;
            vec![byte; spec["sizeBytes"].as_u64().expect("fill size") as usize]
        }
        "pattern" => (0..spec["sizeBytes"].as_u64().expect("pattern size"))
            .map(|i| (i & 0xff) as u8)
            .collect(),
        other => panic!("unknown payload kind {other}"),
    }
}

#[test]
fn shared_chunking_vectors_match() {
    let doc = vectors();
    let cases = doc["cases"].as_array().expect("cases");
    assert!(!cases.is_empty());
    for case in cases {
        let name = case["name"].as_str().unwrap();
        let bytes = payload(case);
        let chunk_size = case["chunkSize"].as_u64().unwrap() as usize;
        assert_eq!(
            bytes.len() as u64,
            case["sizeBytes"].as_u64().unwrap(),
            "vector {name}: payload size"
        );
        let expected_root = case["rootCid"].as_str().unwrap();
        let kind = case["expectedRootKind"].as_str().unwrap();

        assert_eq!(
            content_cid(&bytes, chunk_size),
            expected_root,
            "vector {name}: root CID"
        );
        let (leaves, total) = leaf_cids_for(&bytes, chunk_size);
        if kind == "raw" {
            assert!(
                bytes.len() <= chunk_size,
                "vector {name}: raw kind too large"
            );
            // Empty content has no chunk at all; otherwise exactly one.
            assert!(
                leaves.len() <= 1,
                "vector {name}: at most one leaf expected"
            );
            if bytes.is_empty() {
                assert_eq!(
                    expected_root,
                    cid_for_raw(b""),
                    "vector {name}: empty raw CID"
                );
            } else {
                assert_eq!(leaves[0], expected_root);
            }
            continue;
        }
        assert!(
            bytes.len() > chunk_size,
            "vector {name}: manifest kind too small"
        );
        assert!(leaves.len() > 1, "vector {name}: manifest needs > 1 leaf");
        let tree = manifest_tree(chunk_size as u32, total, &leaves).unwrap();
        assert_eq!(tree.root_cid, expected_root, "vector {name}: tree root");
        let root = tree.manifests.last().unwrap();
        assert_eq!(
            root.bytes.len() as u64,
            case["rootManifestBytesLength"].as_u64().unwrap(),
            "vector {name}: root manifest byte length"
        );
        if let Some(hex_bytes) = case["rootManifestBytesHex"].as_str() {
            assert_eq!(
                hex::encode(&root.bytes),
                hex_bytes,
                "vector {name}: canonical manifest bytes"
            );
        }
        if let Some(children) = case["leafManifestCids"].as_array() {
            let actual: Vec<&str> = tree.manifests[..children.len()]
                .iter()
                .map(|node| node.cid.as_str())
                .collect();
            let expected: Vec<&str> = children.iter().map(|c| c.as_str().unwrap()).collect();
            assert_eq!(actual, expected, "vector {name}: leaf manifest CIDs");
        }
        if let Some(leaf_cids) = case["leafCids"].as_array() {
            let actual: Vec<&str> = leaves.iter().map(String::as_str).collect();
            let expected: Vec<&str> = leaf_cids.iter().map(|c| c.as_str().unwrap()).collect();
            assert_eq!(actual, expected, "vector {name}: leaf CIDs");
        }
    }
}

#[test]
fn shared_chunking_rejects_match() {
    let doc = vectors();
    for case in doc["rejects"].as_array().expect("rejects") {
        let name = case["name"].as_str().unwrap();
        let chunk_size = case["chunkSize"].as_u64().unwrap() as u32;
        let content_length = case["contentLength"].as_u64().unwrap();
        let leaf_count = case["leafCount"].as_u64().unwrap() as usize;
        let leaves: Vec<String> = (0..leaf_count)
            .map(|i| cid_for_raw(format!("leaf-{i}").as_bytes()))
            .collect();
        match name {
            "non_raw_cid_rejected" | "non_sha256_multihash_rejected" | "malformed_cid_rejected" => {
                let cid = case["cid"].as_str().unwrap();
                // Guard: these inputs are otherwise valid, so the rejection can
                // only come from the leaf CID itself.
                assert!(
                    manifest_tree(chunk_size, content_length, &leaves).is_ok(),
                    "vector {name}: leaf count must be valid for the CID-reject guard"
                );
                assert!(
                    parse_cid(cid).is_err(),
                    "vector {name}: {cid} must be rejected"
                );
                let mut poisoned = leaves.clone();
                poisoned[0] = cid.to_string();
                assert!(
                    manifest_tree(chunk_size, content_length, &poisoned).is_err(),
                    "vector {name}: manifest_tree must reject the leaf CID"
                );
            }
            "single_block_content_has_no_manifest"
            | "wrong_leaf_count_rejected"
            | "zero_chunk_size_rejected" => {
                assert!(
                    manifest_tree(chunk_size, content_length, &leaves).is_err(),
                    "vector {name}: manifest_tree must reject these inputs"
                );
            }
            other => panic!("unknown reject vector {other}"),
        }
    }
}

#[test]
fn content_cid_is_deterministic_across_calls() {
    let bytes: Vec<u8> = (0..(CHUNK_SIZE + 7)).map(|i| (i & 0xff) as u8).collect();
    let a = content_cid(&bytes, CHUNK_SIZE);
    let b = content_cid(&bytes, CHUNK_SIZE);
    let c = content_cid(&bytes, CHUNK_SIZE);
    assert_eq!(a, b);
    assert_eq!(b, c);
}

#[test]
fn manifest_root_covers_chunk_size_and_total_length() {
    use conex_proto::cid::content_cid_for_parts;
    let chunk_size = 1024u32;
    let bytes: Vec<u8> = (0..(chunk_size as usize * 3))
        .map(|i| (i & 0xff) as u8)
        .collect();
    let (leaves, total) = leaf_cids_for(&bytes, chunk_size as usize);
    assert_eq!(leaves.len(), 3);
    let root = content_cid_for_parts(chunk_size, total, &leaves).unwrap();
    assert_eq!(root, content_cid(&bytes, chunk_size as usize));

    // Same leaves, shorter total length that still yields three leaves.
    let shorter = content_cid_for_parts(chunk_size, total - 72, &leaves).unwrap();
    assert_ne!(root, shorter, "root must bind the total content length");

    // Same leaves, wider chunk size that still yields three leaves.
    let wider = content_cid_for_parts(chunk_size + 76, total, &leaves).unwrap();
    assert_ne!(root, wider, "root must bind the chunk size");
}
