[package]
name = "conex-core"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
conex-proto = { path = "../conex-proto" }
http.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
async-trait.workspace = true
