[package]
name = "conex-host"
version.workspace = true
edition.workspace = true

[[bin]]
name = "conex-host"
path = "src/main.rs"

[dependencies]
async-trait.workspace = true
axum.workspace = true
axum-server.workspace = true
conex-assembly = { path = "../conex-assembly" }
conex-core = { path = "../conex-core" }
conex-proto = { path = "../conex-proto" }
conex-transport-http = { path = "../conex-transport-http" }
hex.workspace = true
pbjson-types.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
toml.workspace = true

[dev-dependencies]
async-trait.workspace = true
axum.workspace = true
bytes.workspace = true
conex-transport-http = { path = "../conex-transport-http" }
hex.workspace = true
http.workspace = true
rcgen.workspace = true
sha2.workspace = true
conex-core = { path = "../conex-core" }
conex-provider-fs = { path = "../conex-provider-fs" }
conex-proto = { path = "../conex-proto" }
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time", "test-util", "net", "io-util", "signal"] }
