//! WSS bootstrap state machine (design §4.4, §5.2).
//!
//! The conex WSS Link runs a fixed-format handshake before any business
//! frame is allowed:
//!
//!   hello → hello result → conex/ready → ready result
//!
//! - Both sides speak UTF-8 JSON-RPC 2.0; one JSON message = one WS text
//!   message; each JSON message ≤ 64 KiB.
//! - `conex/ready` echoes a server-generated one-shot `negotiation_id`.
//! - Until the server writes `ready result`, the client may NOT send any
//!   business frame. After it does, the client may send the first
//!   business frame.
//! - The server may not advertise a profile that differs from `hello`;
//!   repeated `ready` is rejected.
//!
//! This module is a pure state machine; no Tokio / WS I/O. The transport
//! crate (`conex-transport-ws`) is responsible for wiring it onto axum/hyper.
#![forbid(unsafe_code)]

use std::fmt;

use serde::{Deserialize, Serialize};
use thiserror::Error;

use conex_proto::v1;

/// UTF-8 JSON-RPC 2.0 envelope, capped at 64 KiB per message.
pub const MAX_BOOTSTRAP_MESSAGE_BYTES: usize = 65_536;

/// Default handshake timeout: 10 seconds.
pub const DEFAULT_HANDSHAKE_TIMEOUT_MS: u64 = 10_000;

/// Identifier for the two bootstrap profiles the demo slice recognises.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProfileId {
    #[serde(rename = "conex-jsonrpc2-wss-v1")]
    JsonRpc2WssV1,
    #[serde(rename = "conex-protobuf-wss-v1")]
    ProtobufWssV1,
}

impl ProfileId {
    pub fn as_str(&self) -> &'static str {
        match self {
            ProfileId::JsonRpc2WssV1 => "conex-jsonrpc2-wss-v1",
            ProfileId::ProtobufWssV1 => "conex-protobuf-wss-v1",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BootstrapState {
    AwaitingHello,
    SentHello,
    AwaitingReady,
    Ready {
        profile: ProfileId,
        negotiation_id: String,
    },
    Failed {
        reason: BootstrapError,
    },
}

#[derive(Debug, Error, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum BootstrapError {
    #[error("early business frame before ready result")]
    EarlyBusiness,
    #[error("malformed bootstrap envelope: {0}")]
    MalformedEnvelope(String),
    #[error("unknown method: {0}")]
    UnknownMethod(String),
    #[error("unsupported profile: {0}")]
    UnsupportedProfile(String),
    #[error("repeated ready call")]
    RepeatedReady,
    #[error("ready negotiation id mismatch")]
    NegotiationIdMismatch,
    #[error("handshake timeout")]
    Timeout,
    #[error("buffer exceeded {MAX_BOOTSTRAP_MESSAGE_BYTES} bytes")]
    BufferExceeded,
    #[error("missing plane")]
    MissingPlane,
    #[error("plane mismatch: client said {client}, server expected {server}")]
    PlaneMismatch { client: String, server: String },
}

pub fn plane_name(plane: v1::Plane) -> &'static str {
    match plane {
        v1::Plane::Broker => "broker",
        v1::Plane::Relay => "relay",
        v1::Plane::Unspecified => "unspecified",
    }
}

fn plane_from_str(s: &str) -> Option<v1::Plane> {
    match s {
        "broker" => Some(v1::Plane::Broker),
        "relay" => Some(v1::Plane::Relay),
        _ => None,
    }
}

/// `v1::Plane` is generated by prost as SCREAMING_SNAKE JSON. Wrap it so
/// hello/ready envelopes use the lowercase wire spelling.
mod plane_serde {
    use super::{plane_from_str, plane_name, v1};
    use serde::{Deserialize, Deserializer, Serializer};

    pub fn serialize<S: Serializer>(plane: &v1::Plane, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(plane_name(*plane))
    }
    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<v1::Plane, D::Error> {
        let s = String::deserialize(d)?;
        plane_from_str(&s).ok_or_else(|| serde::de::Error::custom(format!("unknown plane: {s}")))
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HelloRequest {
    pub profile_id: String,
    #[serde(with = "plane_serde")]
    pub plane: v1::Plane,
    pub provides: Vec<String>,
    pub requires: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReadyRequest {
    pub negotiation_id: String,
    pub profile_id: String,
    #[serde(with = "plane_serde")]
    pub plane: v1::Plane,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BootstrapFrame {
    pub json: String,
}

fn profile_from_str(s: &str) -> Option<ProfileId> {
    match s {
        "conex-jsonrpc2-wss-v1" => Some(ProfileId::JsonRpc2WssV1),
        "conex-protobuf-wss-v1" => Some(ProfileId::ProtobufWssV1),
        _ => None,
    }
}

fn generate_negotiation_id() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0);
    format!("neg-{nanos:016x}")
}

fn default_limits_json() -> serde_json::Value {
    serde_json::json!({
        "maxFrameBytes": 1_048_576u32,
        "maxInflight": 4u32,
        "maxQueuedBytes": 8_388_608u32,
        "timeoutMs": 8_000u32,
    })
}

/// Server-side handshake.
pub struct ServerHandshake {
    state: BootstrapState,
    negotiation_id: String,
    server_profile: ProfileId,
    server_plane: v1::Plane,
}

impl ServerHandshake {
    pub fn new(server_profile: ProfileId, server_plane: v1::Plane) -> Self {
        Self {
            state: BootstrapState::AwaitingHello,
            negotiation_id: generate_negotiation_id(),
            server_profile,
            server_plane,
        }
    }

    pub fn state(&self) -> &BootstrapState {
        &self.state
    }

    pub fn negotiation_id(&self) -> &str {
        &self.negotiation_id
    }

    pub fn ingest(&mut self, frame: BootstrapFrame) -> Result<BootstrapFrame, BootstrapError> {
        if frame.json.len() > MAX_BOOTSTRAP_MESSAGE_BYTES {
            return Err(BootstrapError::BufferExceeded);
        }
        let parsed: serde_json::Value = serde_json::from_str(&frame.json)
            .map_err(|e| BootstrapError::MalformedEnvelope(e.to_string()))?;
        match self.state.clone() {
            BootstrapState::AwaitingHello => self.handle_hello(parsed),
            BootstrapState::AwaitingReady => self.handle_frame_after_hello(parsed),
            BootstrapState::Ready { .. } => Err(BootstrapError::EarlyBusiness),
            _ => Err(BootstrapError::MalformedEnvelope(
                "server in unexpected state".into(),
            )),
        }
    }

    fn handle_hello(&mut self, value: serde_json::Value) -> Result<BootstrapFrame, BootstrapError> {
        let method = value
            .get("method")
            .and_then(|v| v.as_str())
            .ok_or_else(|| BootstrapError::MalformedEnvelope("missing method".into()))?;
        if method != "conex/hello" {
            return Err(BootstrapError::UnknownMethod(method.to_string()));
        }
        let params = value
            .get("params")
            .ok_or_else(|| BootstrapError::MalformedEnvelope("missing params".into()))?;
        let req: HelloRequest = serde_json::from_value(params.clone())
            .map_err(|e| BootstrapError::MalformedEnvelope(e.to_string()))?;
        let server_profile_str = self.server_profile.as_str();
        if req.profile_id != server_profile_str {
            return Err(BootstrapError::UnsupportedProfile(req.profile_id));
        }
        if req.plane != self.server_plane {
            return Err(BootstrapError::PlaneMismatch {
                client: plane_name(req.plane).to_string(),
                server: plane_name(self.server_plane).to_string(),
            });
        }
        let response = serde_json::json!({
            "jsonrpc": "2.0",
            "id": value.get("id").cloned().unwrap_or(serde_json::Value::Null),
            "result": {
                "negotiationId": self.negotiation_id,
                "profileId": server_profile_str,
                "plane": plane_name(req.plane),
                "limits": default_limits_json(),
                "provides": req.provides,
                "requires": req.requires,
            }
        });
        let json = serde_json::to_string(&response)
            .map_err(|e| BootstrapError::MalformedEnvelope(e.to_string()))?;
        self.state = BootstrapState::AwaitingReady;
        Ok(BootstrapFrame { json })
    }

    fn handle_frame_after_hello(
        &mut self,
        value: serde_json::Value,
    ) -> Result<BootstrapFrame, BootstrapError> {
        let method = value
            .get("method")
            .and_then(|v| v.as_str())
            .ok_or_else(|| BootstrapError::MalformedEnvelope("missing method".into()))?;
        match method {
            "conex/ready" => self.handle_ready(value),
            "conex/hello" => Err(BootstrapError::MalformedEnvelope(
                "conex/hello received after handshake started".into(),
            )),
            _ => Err(BootstrapError::UnknownMethod(method.to_string())),
        }
    }

    fn handle_ready(&mut self, value: serde_json::Value) -> Result<BootstrapFrame, BootstrapError> {
        if matches!(self.state, BootstrapState::Ready { .. }) {
            return Err(BootstrapError::RepeatedReady);
        }
        let method = value
            .get("method")
            .and_then(|v| v.as_str())
            .ok_or_else(|| BootstrapError::MalformedEnvelope("missing method".into()))?;
        if method != "conex/ready" {
            return Err(BootstrapError::UnknownMethod(method.to_string()));
        }
        let params = value
            .get("params")
            .ok_or_else(|| BootstrapError::MalformedEnvelope("missing params".into()))?;
        let req: ReadyRequest = serde_json::from_value(params.clone())
            .map_err(|e| BootstrapError::MalformedEnvelope(e.to_string()))?;
        if req.profile_id != self.server_profile.as_str() {
            return Err(BootstrapError::UnsupportedProfile(req.profile_id));
        }
        if req.negotiation_id != self.negotiation_id {
            return Err(BootstrapError::NegotiationIdMismatch);
        }
        if req.plane != self.server_plane {
            return Err(BootstrapError::PlaneMismatch {
                client: plane_name(req.plane).to_string(),
                server: plane_name(self.server_plane).to_string(),
            });
        }
        let response = serde_json::json!({
            "jsonrpc": "2.0",
            "id": value.get("id").cloned().unwrap_or(serde_json::Value::Null),
            "result": {
                "negotiationId": self.negotiation_id,
                "profileId": self.server_profile.as_str(),
                "plane": plane_name(self.server_plane),
            }
        });
        let json = serde_json::to_string(&response)
            .map_err(|e| BootstrapError::MalformedEnvelope(e.to_string()))?;
        self.state = BootstrapState::Ready {
            profile: self.server_profile,
            negotiation_id: self.negotiation_id.clone(),
        };
        Ok(BootstrapFrame { json })
    }
}

/// Client-side handshake.
pub struct ClientHandshake {
    state: BootstrapState,
    expected_negotiation_id: String,
    agreed_profile: Option<ProfileId>,
    server_hello_plane: v1::Plane,
    server_hello_profile: String,
    server_hello_id: Option<serde_json::Value>,
    request_counter: u64,
}

impl Default for ClientHandshake {
    fn default() -> Self {
        Self::new()
    }
}

impl ClientHandshake {
    pub fn new() -> Self {
        Self {
            state: BootstrapState::AwaitingHello,
            expected_negotiation_id: String::new(),
            agreed_profile: None,
            server_hello_plane: v1::Plane::Broker,
            server_hello_profile: String::new(),
            server_hello_id: None,
            request_counter: 0,
        }
    }

    pub fn state(&self) -> &BootstrapState {
        &self.state
    }

    pub fn build_hello(
        &mut self,
        profile: ProfileId,
        plane: v1::Plane,
        provides: Vec<String>,
        requires: Vec<String>,
    ) -> Result<BootstrapFrame, BootstrapError> {
        if !matches!(self.state, BootstrapState::AwaitingHello) {
            return Err(BootstrapError::RepeatedReady);
        }
        if plane == v1::Plane::Unspecified {
            return Err(BootstrapError::MissingPlane);
        }
        self.request_counter += 1;
        let id = format!("req-{}", self.request_counter);
        let hello = serde_json::json!({
            "jsonrpc": "2.0",
            "id": id,
            "method": "conex/hello",
            "params": {
                "profileId": profile.as_str(),
                "plane": plane_name(plane),
                "provides": provides,
                "requires": requires,
            }
        });
        let json = serde_json::to_string(&hello)
            .map_err(|e| BootstrapError::MalformedEnvelope(e.to_string()))?;
        self.agreed_profile = Some(profile);
        self.state = BootstrapState::SentHello;
        Ok(BootstrapFrame { json })
    }

    pub fn ingest(&mut self, frame: BootstrapFrame) -> Result<ReadyRequest, BootstrapError> {
        if frame.json.len() > MAX_BOOTSTRAP_MESSAGE_BYTES {
            return Err(BootstrapError::BufferExceeded);
        }
        let parsed: serde_json::Value = serde_json::from_str(&frame.json)
            .map_err(|e| BootstrapError::MalformedEnvelope(e.to_string()))?;
        match self.state.clone() {
            BootstrapState::AwaitingHello => Err(BootstrapError::MalformedEnvelope(
                "client received before sending hello".into(),
            )),
            BootstrapState::SentHello => {
                let result = parsed
                    .get("result")
                    .ok_or_else(|| BootstrapError::MalformedEnvelope("missing result".into()))?;
                let negotiation_id = result
                    .get("negotiationId")
                    .and_then(|v| v.as_str())
                    .ok_or_else(|| {
                        BootstrapError::MalformedEnvelope("missing negotiationId".into())
                    })?
                    .to_string();
                let profile_str = result
                    .get("profileId")
                    .and_then(|v| v.as_str())
                    .ok_or_else(|| BootstrapError::MalformedEnvelope("missing profileId".into()))?
                    .to_string();
                let profile = profile_from_str(&profile_str)
                    .ok_or_else(|| BootstrapError::UnsupportedProfile(profile_str.clone()))?;
                if Some(profile) != self.agreed_profile {
                    return Err(BootstrapError::UnsupportedProfile(profile_str));
                }
                let plane_str = result
                    .get("plane")
                    .and_then(|v| v.as_str())
                    .ok_or_else(|| BootstrapError::MalformedEnvelope("missing plane".into()))?
                    .to_string();
                let plane = plane_from_str(&plane_str).ok_or_else(|| {
                    BootstrapError::MalformedEnvelope(format!("unknown plane: {plane_str}"))
                })?;
                self.expected_negotiation_id = negotiation_id.clone();
                self.server_hello_plane = plane;
                self.server_hello_profile = profile_str.clone();
                self.server_hello_id = parsed.get("id").cloned();
                self.state = BootstrapState::AwaitingReady;
                Ok(ReadyRequest {
                    negotiation_id,
                    profile_id: profile_str,
                    plane,
                })
            }
            BootstrapState::AwaitingReady => {
                let result = parsed
                    .get("result")
                    .ok_or_else(|| BootstrapError::MalformedEnvelope("missing result".into()))?;
                let negotiation_id = result
                    .get("negotiationId")
                    .and_then(|v| v.as_str())
                    .ok_or_else(|| {
                        BootstrapError::MalformedEnvelope("missing negotiationId".into())
                    })?
                    .to_string();
                if negotiation_id != self.expected_negotiation_id {
                    return Err(BootstrapError::NegotiationIdMismatch);
                }
                self.state = BootstrapState::Ready {
                    profile: self.agreed_profile.unwrap_or(ProfileId::JsonRpc2WssV1),
                    negotiation_id: self.expected_negotiation_id.clone(),
                };
                Ok(ReadyRequest {
                    negotiation_id,
                    profile_id: self.server_hello_profile.clone(),
                    plane: self.server_hello_plane,
                })
            }
            BootstrapState::Ready { .. } => Err(BootstrapError::RepeatedReady),
            BootstrapState::Failed { .. } => Err(BootstrapError::MalformedEnvelope(
                "client already failed".into(),
            )),
        }
    }

    pub fn build_ready_frame(
        &self,
        ready: &ReadyRequest,
    ) -> Result<BootstrapFrame, BootstrapError> {
        let frame = serde_json::json!({
            "jsonrpc": "2.0",
            "id": self.server_hello_id.clone().unwrap_or(serde_json::Value::Null),
            "method": "conex/ready",
            "params": {
                "negotiationId": ready.negotiation_id,
                "profileId": ready.profile_id,
                "plane": plane_name(ready.plane),
            }
        });
        let json = serde_json::to_string(&frame)
            .map_err(|e| BootstrapError::MalformedEnvelope(e.to_string()))?;
        Ok(BootstrapFrame { json })
    }
}

impl fmt::Display for BootstrapFrame {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.json)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bootstrap_happy_path_round_trip() {
        let mut server = ServerHandshake::new(ProfileId::JsonRpc2WssV1, v1::Plane::Broker);
        let mut client = ClientHandshake::new();
        let hello = client
            .build_hello(
                ProfileId::JsonRpc2WssV1,
                v1::Plane::Broker,
                vec!["source/read".into()],
                vec![],
            )
            .unwrap();
        let hello_result = server.ingest(hello).unwrap();
        let ready = client.ingest(hello_result).unwrap();
        let ready_frame = client.build_ready_frame(&ready).unwrap();
        let ready_result = server.ingest(ready_frame).unwrap();
        let _ = client.ingest(ready_result).unwrap();
        assert!(matches!(server.state(), BootstrapState::Ready { .. }));
        assert!(matches!(client.state(), BootstrapState::Ready { .. }));
    }

    #[test]
    fn profile_mismatch_rejected() {
        let mut server = ServerHandshake::new(ProfileId::JsonRpc2WssV1, v1::Plane::Broker);
        let hello = serde_json::json!({
            "jsonrpc": "2.0",
            "id": "req-1",
            "method": "conex/hello",
            "params": {
                "profileId": "conex-protobuf-wss-v1",
                "plane": "broker",
                "provides": [],
                "requires": [],
            }
        })
        .to_string();
        let err = server.ingest(BootstrapFrame { json: hello }).unwrap_err();
        assert!(matches!(err, BootstrapError::UnsupportedProfile(_)));
    }

    #[test]
    fn plane_mismatch_rejected() {
        let mut server = ServerHandshake::new(ProfileId::JsonRpc2WssV1, v1::Plane::Broker);
        let hello = serde_json::json!({
            "jsonrpc": "2.0",
            "id": "req-1",
            "method": "conex/hello",
            "params": {
                "profileId": "conex-jsonrpc2-wss-v1",
                "plane": "relay",
                "provides": [],
                "requires": [],
            }
        })
        .to_string();
        let err = server.ingest(BootstrapFrame { json: hello }).unwrap_err();
        assert!(matches!(err, BootstrapError::PlaneMismatch { .. }));
    }

    #[test]
    fn unknown_method_rejected() {
        let mut server = ServerHandshake::new(ProfileId::JsonRpc2WssV1, v1::Plane::Broker);
        let bad = serde_json::json!({
            "jsonrpc": "2.0",
            "id": "req-1",
            "method": "conex/foobar",
            "params": {
                "profileId": "conex-jsonrpc2-wss-v1",
                "plane": "broker",
            }
        })
        .to_string();
        let err = server.ingest(BootstrapFrame { json: bad }).unwrap_err();
        assert!(matches!(err, BootstrapError::UnknownMethod(_)));
    }

    #[test]
    fn repeated_hello_rejected_after_hello() {
        let mut server = ServerHandshake::new(ProfileId::JsonRpc2WssV1, v1::Plane::Broker);
        let mut client = ClientHandshake::new();
        let hello = client
            .build_hello(ProfileId::JsonRpc2WssV1, v1::Plane::Broker, vec![], vec![])
            .unwrap();
        let _ = server.ingest(hello.clone()).unwrap();
        let second = server.ingest(hello);
        assert!(matches!(second, Err(BootstrapError::MalformedEnvelope(_))));
    }

    #[test]
    fn ready_frame_after_ready_rejected_as_early_business() {
        let mut server = ServerHandshake::new(ProfileId::JsonRpc2WssV1, v1::Plane::Broker);
        let mut client = ClientHandshake::new();
        let hello = client
            .build_hello(ProfileId::JsonRpc2WssV1, v1::Plane::Broker, vec![], vec![])
            .unwrap();
        let hello_result = server.ingest(hello).unwrap();
        let ready = client.ingest(hello_result).unwrap();
        let ready_frame = client.build_ready_frame(&ready).unwrap();
        let _ = server.ingest(ready_frame.clone()).unwrap();
        let second = server.ingest(ready_frame);
        assert!(matches!(second, Err(BootstrapError::EarlyBusiness)));
    }

    #[test]
    fn oversized_bootstrap_message_rejected() {
        let mut server = ServerHandshake::new(ProfileId::JsonRpc2WssV1, v1::Plane::Broker);
        let huge = "x".repeat(MAX_BOOTSTRAP_MESSAGE_BYTES + 1);
        let err = server.ingest(BootstrapFrame { json: huge }).unwrap_err();
        assert!(matches!(err, BootstrapError::BufferExceeded));
    }

    #[test]
    fn negotiation_id_mismatch_rejected_after_hello() {
        let mut server = ServerHandshake::new(ProfileId::JsonRpc2WssV1, v1::Plane::Broker);
        let mut client = ClientHandshake::new();
        let hello = client
            .build_hello(ProfileId::JsonRpc2WssV1, v1::Plane::Broker, vec![], vec![])
            .unwrap();
        let hello_result = server.ingest(hello).unwrap();
        let _ = client.ingest(hello_result).unwrap();
        let bad = serde_json::json!({
            "jsonrpc": "2.0",
            "id": "ready-spoof",
            "method": "conex/ready",
            "params": {
                "negotiationId": "spoofed",
                "profileId": "conex-jsonrpc2-wss-v1",
                "plane": "broker",
            }
        })
        .to_string();
        let err = server.ingest(BootstrapFrame { json: bad }).unwrap_err();
        assert!(matches!(err, BootstrapError::NegotiationIdMismatch));
    }

    #[test]
    fn both_profiles_known() {
        let s1 = ProfileId::JsonRpc2WssV1.as_str();
        let s2 = ProfileId::ProtobufWssV1.as_str();
        assert_eq!(s1, "conex-jsonrpc2-wss-v1");
        assert_eq!(s2, "conex-protobuf-wss-v1");
    }

    #[test]
    fn early_business_frame_rejected_after_ready() {
        let mut server = ServerHandshake::new(ProfileId::JsonRpc2WssV1, v1::Plane::Broker);
        let mut client = ClientHandshake::new();
        let hello = client
            .build_hello(ProfileId::JsonRpc2WssV1, v1::Plane::Broker, vec![], vec![])
            .unwrap();
        let hello_result = server.ingest(hello).unwrap();
        let ready = client.ingest(hello_result).unwrap();
        let ready_frame = client.build_ready_frame(&ready).unwrap();
        let _ = server.ingest(ready_frame).unwrap();
        let business = serde_json::json!({
            "jsonrpc": "2.0",
            "id": "biz-1",
            "method": "source/read",
            "params": {}
        })
        .to_string();
        let err = server
            .ingest(BootstrapFrame { json: business })
            .unwrap_err();
        assert!(matches!(err, BootstrapError::EarlyBusiness));
    }

    #[test]
    fn unspecified_plane_rejected_on_hello() {
        let mut client = ClientHandshake::new();
        let err = client
            .build_hello(
                ProfileId::JsonRpc2WssV1,
                v1::Plane::Unspecified,
                vec![],
                vec![],
            )
            .unwrap_err();
        assert!(matches!(err, BootstrapError::MissingPlane));
    }

    #[test]
    fn protobuf_profile_negotiates() {
        let mut server = ServerHandshake::new(ProfileId::ProtobufWssV1, v1::Plane::Broker);
        let mut client = ClientHandshake::new();
        let hello = client
            .build_hello(
                ProfileId::ProtobufWssV1,
                v1::Plane::Broker,
                vec!["blob/commit".into()],
                vec![],
            )
            .unwrap();
        let hello_result = server.ingest(hello).unwrap();
        let ready = client.ingest(hello_result).unwrap();
        assert_eq!(ready.profile_id, "conex-protobuf-wss-v1");
    }
}
