//! P1 canonical chunked-content vectors (design §5.3/§5.4).
//!
//! The golden bytes and root CIDs come from `conformance/vectors/p1/chunking.json`,
//! generated by `conformance/tools/gen_manifest_goldens.py` from `protoc --encode`
//! (C++ protobuf) plus the Python standard library. The TypeScript side must
//! reproduce those bytes exactly through the production `@conex/sdk` helpers —
//! no test-local copy of the rule.
import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";

import {
  ContentAddressError,
  chunkPayload,
  contentCid,
  leafCidsFor,
  manifestTree,
  parseContentCid,
} from "../src/content";

interface PayloadSpec {
  kind: "literal" | "fill" | "pattern";
  value?: string;
  byte?: number;
  sizeBytes?: number;
}

interface Case {
  name: string;
  payload: PayloadSpec;
  chunkSize: number;
  sizeBytes: number;
  expectedRootKind: "raw" | "manifest";
  rootCid: string;
  rootManifestBytesLength?: number;
  rootManifestBytesHex?: string;
  leafManifestCids?: string[];
  leafCids?: string[];
}

interface RejectCase {
  name: string;
  cid?: string;
  chunkSize: number;
  contentLength: number;
  leafCount: number;
}

const vectorsUrl = new URL("../../../conformance/vectors/p1/chunking.json", import.meta.url);
const vectors = JSON.parse(readFileSync(vectorsUrl, "utf8")) as {
  cases: Case[];
  rejects: RejectCase[];
};

function bytesFor(spec: PayloadSpec): Uint8Array {
  if (spec.kind === "literal") {
    return new TextEncoder().encode(spec.value ?? "");
  }
  if (spec.kind === "fill") {
    return new Uint8Array(spec.sizeBytes!).fill(spec.byte!);
  }
  const out = new Uint8Array(spec.sizeBytes!);
  for (let i = 0; i < out.length; i += 1) {
    out[i] = i & 0xff;
  }
  return out;
}

function hex(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString("hex");
}

test("shared chunking vectors match the canonical rule", async () => {
  expect(vectors.cases.length).toBeGreaterThan(0);
  for (const c of vectors.cases) {
    const bytes = bytesFor(c.payload);
    expect(bytes.length, `${c.name}: payload size`).toBe(c.sizeBytes);
    expect(await contentCid(bytes, c.chunkSize), `${c.name}: root CID`).toBe(c.rootCid);

    const { leaves, total } = await leafCidsFor(bytes, c.chunkSize);
    if (c.expectedRootKind === "raw") {
      expect(bytes.length, `${c.name}: raw kind`).toBeLessThanOrEqual(c.chunkSize);
      expect(leaves.length, `${c.name}: leaves`).toBeLessThanOrEqual(1);
      continue;
    }
    expect(bytes.length, `${c.name}: manifest kind`).toBeGreaterThan(c.chunkSize);
    const tree = await manifestTree(c.chunkSize, total, leaves);
    const root = tree.manifests.at(-1)!;
    expect(root.cid, `${c.name}: tree root`).toBe(c.rootCid);
    expect(root.bytes.length, `${c.name}: root manifest length`).toBe(
      c.rootManifestBytesLength!,
    );
    if (c.rootManifestBytesHex !== undefined) {
      expect(hex(root.bytes), `${c.name}: canonical manifest bytes`).toBe(c.rootManifestBytesHex);
    }
    if (c.leafManifestCids !== undefined) {
      expect(tree.manifests.slice(0, c.leafManifestCids.length).map((n) => n.cid)).toEqual(
        c.leafManifestCids,
      );
    }
    if (c.leafCids !== undefined) {
      expect(leaves).toEqual(c.leafCids);
    }
  }
});

test("shared chunking rejects match the canonical rule", async () => {
  for (const c of vectors.rejects) {
    const validLeaves: string[] = [];
    for (let i = 0; i < c.leafCount; i += 1) {
      const { leaves } = await leafCidsFor(new TextEncoder().encode(`leaf-${i}`), 16);
      validLeaves.push(leaves[0]!);
    }

    if (c.cid !== undefined) {
      expect(() => parseContentCid(c.cid!), `${c.name}: ${c.cid} must be rejected`).toThrow(
        ContentAddressError,
      );
      // Guard: the leaf count is valid, so the rejection comes from the CID.
      await manifestTree(c.chunkSize, c.contentLength, validLeaves);
      const poisoned = [...validLeaves];
      poisoned[0] = c.cid;
      await expect(manifestTree(c.chunkSize, c.contentLength, poisoned)).rejects.toThrow(
        ContentAddressError,
      );
      continue;
    }
    await expect(
      manifestTree(c.chunkSize, c.contentLength, validLeaves),
    ).rejects.toThrow(ContentAddressError);
  }
});

test("contentCid is deterministic and chunk-size aware", async () => {
  const chunkSize = 1024;
  const bytes = new Uint8Array(chunkSize * 3);
  for (let i = 0; i < bytes.length; i += 1) {
    bytes[i] = i & 0xff;
  }
  const a = await contentCid(bytes, chunkSize);
  expect(await contentCid(bytes, chunkSize)).toBe(a);
  expect(await contentCid(bytes, chunkSize + 76)).not.toBe(a);
  expect(chunkPayload(bytes, chunkSize).length).toBe(3);
});
